"""Abstract protocols and base contracts for Research Taxonomy repositories."""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol

from src.models.taxonomy_rules import (
    TaxonomyAuditLogDTO,
    TaxonomyProposalDTO,
    TaxonomyRuleDTO,
)

DEFAULT_TAXONOMY_STORAGE_PATH = "data/taxonomy/research_taxonomy.json"


class TaxonomyRepositoryProtocol(Protocol):
    """Abstract protocol contract for research taxonomy storage."""

    def get_all_rules(self, active_only: bool = True) -> List[TaxonomyRuleDTO]: ...
    def get_rule_by_id(self, rule_id: str) -> Optional[TaxonomyRuleDTO]: ...
    def upsert_rule(self, rule: TaxonomyRuleDTO) -> None: ...
    def archive_rule(self, rule_id: str) -> bool: ...
    def delete_rule(self, rule_id: str) -> bool: ...
    def get_all_proposals(self, status: Optional[str] = None) -> List[TaxonomyProposalDTO]: ...
    def get_proposal_by_id(self, proposal_id: str) -> Optional[TaxonomyProposalDTO]: ...
    def save_proposal(self, proposal: TaxonomyProposalDTO) -> None: ...
    def update_proposal_status(
        self,
        proposal_id: str,
        status: str,
        reviewed_by: str,
        reviewed_at: Optional[str] = None,
    ) -> Optional[TaxonomyProposalDTO]: ...
    def approve_proposal_atomic(
        self,
        proposal_id: str,
        rule: TaxonomyRuleDTO,
        audit: TaxonomyAuditLogDTO,
    ) -> Optional[TaxonomyRuleDTO]: ...
    def add_audit_log(self, entry: TaxonomyAuditLogDTO) -> None: ...
    def get_audit_logs(self, limit: int = 100) -> List[TaxonomyAuditLogDTO]: ...
    def get_taxonomy_version(self) -> int: ...
    def increment_taxonomy_version(self) -> int: ...
